FROM golang:1.17.4 as builder

WORKDIR /go/src

COPY go.mod go.sum ./
RUN go mod download

COPY ./ ./

ARG CGO_ENABLED=0
ARG GOOS=linux
ARG GOARCH=amd64
RUN go build \
    -o /bin/feedgen \
    -ldflags '-s -w'

WORKDIR /app
COPY config.yml /app/

# Cannot use ENTRYPOINT with heroku.yml
# ENTRYPOINT ["feedgen"]