endpoint: "github/issues/:user/:repo"
type: template
source:
  http: https://github.com/{{ Param "user" }}/{{ Param "repo" }}/issues
feed:
  title: GitHub Issues - {{ Param "repo" }}
  link:
    href: "{{ .URL }}"
  author:
    name: GitHub
  image:
    url: '{{ .Content.Select ".js-site-favicon[type=\"image/png\"]" | Attr "href" }}'
list: "div[id*=issue_]"
item:
  id: '{{ .ItemContent.Select "a[id*=issue]" | Attr "id" }}'
  title: '{{ .ItemContent.Select "a[id*=issue]" }}'
  author:
    name: '{{ .ItemContent.Select ".opened-by>a" }}'
  link:
    href: '{{ .ItemContent.Select "a[id*=issue]" | Attr "href" }}'
  description: '{{ (.LinkContent.Select "td.d-block").First.Text | Truncate 100 }}'
  content: |
    <img src="{{ .Item.Enclosure.URL | Text }}">
    {{ (.LinkContent.Select "td.d-block").First.HTML }}
  enclosure:
    url: '{{ (.LinkContent.Select "meta[name=\"twitter:image:src\"]").Attr "content" }}'